braze:
  endpoint: https://rest.iad-06.braze.com
  api_key: ef2fa85b-296f-43da-be31-f97f73ee147b
  campaign_id: 55a56d48-8aad-42e7-b178-b0403aa2e278
  send_campaign_messages_endpoint: /campaigns/trigger/send
  get_campaigns_list_endpoint: /campaigns/list

scheduler:
  corePoolSize: 1
  maximumPoolSize: 50
  keepAliveTime: 1000

restclient:
  retry: 3